name: ci

on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
      - 'develop'
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16'
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm test
